application/models/admin.py
# coding=utf-8
import sqlalchemy as sa

from application.models.base import BaseModelMixin
from application.extensions.database import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class Admin(db.Model, BaseModelMixin, UserMixin):
    admin_id = sa.Column(sa.Integer, autoincrement=True, primary_key=True)
    username = sa.Column(sa.String(20), nullable=False)
    password_hash = sa.Column(sa.String(128), nullable=False)

    @property
    def password(self):
        raise AttributeError('password is read-only')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    @classmethod
    def create(cls, username, password):
        admin = Admin()
        admin.username = username
        admin.password = password
        db.session.add(admin)
        db.session.commit()
        return admin

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_id(self):
        return self.admin_id

application/models/base.py
# coding=utf-8
import sqlalchemy as sa
from sqlalchemy import Column


class BaseModelMixin(object):
    created_at = Column(sa.DateTime, server_default=sa.text('current_timestamp()'), index=True)
    updated_at = Column(
        sa.DateTime,
        onupdate=sa.text('current_timestamp()'),
        server_default=sa.text('current_timestamp()'),
        index=True,
    )

application/forms/login.py
# coding=utf-8
from flask_wtf import FlaskForm
from wtforms import fields, validators
from application.models.admin import Admin


class LoginForm(FlaskForm):
    username = fields.StringField(u'用户名', [validators.DataRequired(u'用户名不能为空')])
    password = fields.PasswordField(u'密码', [validators.DataRequired(u'密码不能为空')])

    @property
    def admin(self):
        return Admin.query.filter_by(username=self.username.data).first()

    def validate_username(self, field):
        if not self.admin:
            raise validators.ValidationError(u'用户不存在')

    def validate_password(self, field):
        if self.admin and not self.admin.check_password(field.data):
            raise validators.ValidationError(u'密码错误')

application/__init__.py
from flask import Flask
from application.views.frontend import frontend_blueprint
from application.views.login import login_blueprint

from application.extensions.database import db
from application.extensions.login import login_manager


def create_app(cfg):
    app = Flask(__name__)
    app.config.from_pyfile(cfg)
    configure_blueprints(app)
    configure_extensions(app)
    return app


def configure_blueprints(app):
    app.register_blueprint(frontend_blueprint)
    app.register_blueprint(login_blueprint)


def configure_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)

application/views/frontend.py
# coding=utf-8
from flask import Blueprint, render_template
from flask_login import login_required
from application.forms.login import LoginForm
from application.models.admin import Admin


frontend_blueprint = Blueprint('frontend', __name__)


@frontend_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('frontend/index.html')


@frontend_blueprint.route('/test_form', methods=['GET', 'POST'])
@login_required
def test_form():
    form = LoginForm()
    if form.validate_on_submit():
        pass
    return render_template('frontend/test_form.html', form=form)


@frontend_blueprint.route('/test_table', methods=['GET', 'POST'])
@login_required
def test_table():
    data = Admin.query.paginate()
    return render_template('frontend/test_table.html', data=data)

application/views/login.py
# coding=utf-8
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, logout_user, current_user

from application.forms.login import LoginForm


login_blueprint = Blueprint('login', __name__, url_prefix='/login')


@login_blueprint.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('frontend.index'))
    form = LoginForm()
    if form.validate_on_submit():
        login_user(form.admin)
        return redirect(url_for('frontend.index'))
    return render_template('login/index.html', form=form)


@login_blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('login.index'))

application/templates/_macros.html
{% macro render_pagination(pagination) %}
    <ul class="pagination">
        {% if pagination.has_prev %}
        <li class="paginate_button page-item">
            <a href="{{ url_for(request.endpoint, page=pagination.page - 1, **kwargs) }}" class="page-link">Previous</a>
        </li>
        {% endif %}
        {% for page in pagination.iter_pages() %}
        <li class="paginate_button page-item {{ 'active' if page == pagination.page }}">
            {% if page %}
                {% if page != pagination.page %}
                <a href="{{ url_for(request.endpoint, page=page, **kwargs) }}" class="page-link">{{ page }}</a>
                {% else %}
                <a href="javascript:void(0);" class="page-link">{{ page }}</a>
                {% endif %}
            {% else %}
                <a href="javascript:void(0);" class="page-link">...</a>
            {% endif %}
        </li>
        {% endfor %}
        {% if pagination.has_next %}
        <li class="paginate_button page-item">
            <a href="{{ url_for(request.endpoint, page=pagination.page + 1, **kwargs) }}" class="page-link">Next</a>
        </li>
        {% endif %}
    </ul>
{% endmacro %}

{% macro render_form(form, submit_btn='提交') %}
<form class="form-horizontal" method="post">
    {{ form.hidden_tag() }}
    {{ caller() }}
    <div class="form-group row mb-0">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary waves-effect waves-light mr-1">
                {{ submit_btn }}
            </button>
        </div>
    </div>
</form>
{% endmacro %}

{% macro render_field(field) %}
    <div class="form-group row">
        {{ field.label(class="col-sm-2 col-form-label") }}
        <div class="col-sm-10">
            {{ field(class="form-control") }}
            <ul class="parsley-errors-list">
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endmacro %}

application/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Responsive Bootstrap 4 Admin Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{{ url_for('static', filename='assets/images/favicon.ico') }}">

        <!-- jvectormap -->
        <link href="{{ url_for('static', filename='assets/libs/jqvmap/jqvmap.min.css') }}" rel="stylesheet" />

        <!-- DataTables -->
        <link href="{{ url_for('static', filename='assets/libs/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css"/>
        <link href="{{ url_for('static', filename='assets/libs/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css"/>

        <!-- App css -->
        <link href="{{ url_for('static', filename='assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='assets/css/app.min.css') }}" rel="stylesheet" type="text/css" />

    </head>

    <body>

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Topbar Start -->
            <div class="navbar-custom">
                <ul class="list-unstyled topnav-menu float-right mb-0">
                    <li class="dropdown notification-list">
                        <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                            <span class="pro-user-name ml-1">
                                {{ current_user.username }} <i class="mdi mdi-chevron-down"></i>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                            <!-- item-->
                            <div class="dropdown-item noti-title">
                                <h6 class="m-0">
                                    Welcome !
                                </h6>
                            </div>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item notify-item">
                                <i class="dripicons-help"></i>
                                <span>Support</span>
                            </a>
                            <div class="dropdown-divider"></div>
                            <!-- item-->
                            <a href="{{ url_for('login.logout') }}" class="dropdown-item notify-item">
                                <i class="dripicons-power"></i>
                                <span>Logout</span>
                            </a>
                        </div>
                    </li>

                </ul>

                <ul class="list-unstyled menu-left mb-0">
                    <li class="float-left">
                        <a href="{{ url_for('frontend.index') }}" class="logo">
                            <span class="logo-lg">
                                <img src="{{ url_for('static', filename='assets/images/logo-light.png') }}" alt="" height="22">
                            </span>
                            <span class="logo-sm">
                                <img src="{{ url_for('static', filename='assets/images/logo-sm.png') }}" alt="" height="24">
                            </span>
                        </a>
                    </li>
                    <li class="float-left">
                        <a class="button-menu-mobile navbar-toggle">
                            <div class="lines">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="left-side-menu">
                <div class="slimscroll-menu">
                    <div id="sidebar-menu">

                        <ul class="metismenu" id="side-menu">

                            <li class="menu-title">Navigation</li>

                            <li>
                                <a href="{{ url_for('frontend.index') }}">
                                    <i class="dripicons-meter"></i>
                                    <span> Dashboard </span>
                                </a>
                            </li>

                            <li>
                                <a href="javascript: void(0);">
                                    <i class="dripicons-mail"></i>
                                    <span> 示例 </span>
                                    <span class="menu-arrow"></span>
                                </a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li>
                                        <a href="{{ url_for('frontend.test_form') }}">表单页</a>
                                    </li>
                                    <li>
                                        <a href="{{ url_for('frontend.test_table') }}">表格</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>

            </div>
            <div class="content-page">
                <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <h4 class="page-title">Dashboard</h4>
                                </div>
                            </div>
                        </div>
                        {% block main %}
                        {% endblock %}
                    </div> <!-- container -->
                </div> <!-- content -->

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                2018 - 2019 &copy; Greeva theme by <a href="#">Coderthemes</a>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->

            </div>

        </div>
        <!-- END wrapper -->

        <!-- Vendor js -->
        <script src="{{ url_for('static', filename='assets/js/vendor.min.js') }}"></script>

        <!-- KNOB JS -->
        <script src="{{ url_for('static', filename='assets/libs/jquery-knob/jquery.knob.min.js') }}"></script>
        <!-- Chart JS -->
        <script src="{{ url_for('static', filename='assets/libs/chart-js/Chart.bundle.min.js') }}"></script>

        <!-- Jvector map -->
        <script src="{{ url_for('static', filename='assets/libs/jqvmap/jquery.vmap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='assets/libs/jqvmap/jquery.vmap.usa.js') }}"></script>

        <!-- Datatable js -->
        <script src="{{ url_for('static', filename='assets/libs/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ url_for('static', filename='assets/libs/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <script src="{{ url_for('static', filename='assets/libs/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ url_for('static', filename='assets/libs/datatables/responsive.bootstrap4.min.js') }}"></script>

        {% block js %}
        {% endblock %}


        <!-- App js -->
        <script src="{{ url_for('static', filename='assets/js/app.min.js') }}"></script>

    </body>
</html>

application/templates/frontend/index.html
{% extends "base_layout.html" %}
{% block js %}
    <!-- Dashboard Init JS -->
    <script src="{{ url_for('static', filename='assets/js/pages/dashboard.init.js') }}"></script>
{% endblock %}
{% block main %}
    <div class="row">
        <div class="col-xl-4">
            <div class="card-box">
                <div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown"
                       aria-expanded="false">
                        <i class="mdi mdi-dots-horizontal"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Settings</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Download</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Upload</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Action</a>
                    </div>
                </div>
                <h4 class="header-title">Daily Sales</h4>
                <p class="text-muted">March 26 - April 01</p>
                <div class="mb-3 mt-4">
                    <div class="float-right d-none d-xl-block">
                        <img src="{{ url_for('static', filename='assets/images/cards/visa.png') }}" alt="user-card"
                             height="28"/>
                        <img src="{{ url_for('static', filename='assets/images/cards/master.png') }}" alt="user-card"
                             height="28"/>
                        <img src="{{ url_for('static', filename='assets/images/cards/american-express.png') }}"
                             alt="user-card" height="28"/>
                    </div>
                    <h2 class="font-weight-light">$8,459.56</h2>
                </div>
                <div class="chartjs-chart dash-sales-chart">
                    <canvas id="sales-chart"></canvas>
                </div>
            </div><!-- end card-box-->

            <div class="card-box widget-chart-one gradient-success bx-shadow-lg">
                <div class="float-left" dir="ltr">
                    <input data-plugin="knob" data-width="80" data-height="80" data-linecap=round
                           data-fgColor="#ffffff" data-bgcolor="rgba(255,255,255,0.2)" value="49" data-skin="tron"
                           data-angleOffset="180"
                           data-readOnly=true data-thickness=".1"/>
                </div>
                <div class="widget-chart-one-content text-right">
                    <p class="text-white mb-0 mt-2">Statistics</p>
                    <h3 class="text-white">$714</h3>
                </div>
            </div> <!-- end card-box-->

        </div> <!-- end col -->

        <div class="col-xl-4">
            <div class="card-box">
                <div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown"
                       aria-expanded="false">
                        <i class="mdi mdi-dots-horizontal"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Settings</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Download</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Upload</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Action</a>
                    </div>
                </div>
                <h4 class="header-title mb-3">Statistics</h4>
                <div class="row text-center">
                    <div class="col-sm-4 mb-3">
                        <h3 class="font-weight-light">4,335</h3>
                        <p class="text-muted text-overflow">Total Sales</p>
                    </div>
                    <div class="col-sm-4 mb-3">
                        <h3 class="font-weight-light">874</h3>
                        <p class="text-muted text-overflow">Open Compaign</p>
                    </div>
                    <div class="col-sm-4 mb-3">
                        <h3 class="font-weight-light">2,548</h3>
                        <p class="text-muted text-overflow">Total Sales</p>
                    </div>
                </div>
                <div class="chartjs-chart high-performing-product">
                    <canvas id="high-performing-product"></canvas>
                </div>
            </div> <!-- end card-box-->
        </div> <!-- end col -->

        <div class="col-xl-4">
            <div class="card-box">
                <div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown"
                       aria-expanded="false">
                        <i class="mdi mdi-dots-horizontal"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Settings</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Download</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Upload</a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item">Action</a>
                    </div>
                </div>
                <h4 class="header-title mb-3">Total Revenue</h4>
                <div class="row text-center">
                    <div class="col-6 mb-3">
                        <h3 class="font-weight-light">8,459</h3>
                        <p class="text-muted text-overflow">Total Sales</p>
                    </div>
                    <div class="col-6 mb-3">
                        <h3 class="font-weight-light">584</h3>
                        <p class="text-muted text-overflow">Open Compaign</p>
                    </div>
                </div>
                <div class="chartjs-chart conversion-chart">
                    <canvas id="conversion-chart"></canvas>
                </div>
            </div>  <!-- end card-box-->
        </div> <!-- end col -->
    </div>
{% endblock %}

application/templates/frontend/test_form.html
{% extends "base_layout.html" %}
{% from "_macros.html" import render_form, render_field %}
{% block main %}
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                {% call render_form(form) %}
                    {{ render_field(form.username) }}
                    {{ render_field(form.password) }}
                {% endcall %}
            </div>
        </div>
    </div>
{% endblock %}

application/templates/frontend/test_table.html
{% extends "base_layout.html" %}
{% from "_macros.html" import render_pagination %}
{% block main %}
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="dataTables_wrapper dt-bootstrap4 no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered table-sm">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Username</th>
                                    <th>Created At</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for account in data.items %}
                                <tr>
                                    <th scope="row">{{ loop.index }}</th>
                                    <td>{{ account.username }}</td>
                                    <td>{{ account.created_at }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12 col-md-5">
                            <div class="dataTables_info" id="selection-datatable_info" role="status" aria-live="polite">
                                共 {{ data.total }} 条数据
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-7">
                            <div class="dataTables_paginate">
                                {{ render_pagination(data) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

application/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>登录</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{{ url_for('static', filename='assets/images/favicon.ico') }}">
        <!-- App css -->
        <link href="{{ url_for('static', filename='assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='assets/css/app.min.css') }}" rel="stylesheet" type="text/css" />

    </head>

    <body class="authentication-bg authentication-bg-pattern d-flex align-items-center">
        <div class="account-pages w-100 mt-5 mb-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card">
                            <div class="card-body p-4">
                                <form method="post" class="pt-2">
                                    {{ form.hidden_tag() }}
                                    <div class="form-group mb-3">
                                        <label for="username">用户名</label>
                                        <input class="form-control" type="text" id="username" name="username" required="" placeholder="Enter your username">
                                        {% for error in form.username.errors %}
                                        <ul class="parsley-errors-list filled"><li class="parsley-required">{{ error }}</li></ul>
                                        {% endfor %}
                                    </div>
                                    <div class="form-group mb-3">
                                        <label for="password">密码</label>
                                        <input class="form-control" type="password" name="password" required="" id="password" placeholder="Enter your password">
                                        {% for error in form.password.errors %}
                                        <ul class="parsley-errors-list filled"><li class="parsley-required">{{ error }}</li></ul>
                                        {% endfor %}
                                    </div>
                                    <div class="form-group mb-0 text-center">
                                        <button class="btn btn-success btn-block" type="submit"> 登录 </button>
                                    </div>
                                </form>
                                <!-- end row -->
                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->
                    </div> <!-- end col -->
                </div>
            </div>
        </div>
        <!-- end page -->

        <!-- Vendor js -->
        <script src="{{ url_for('static', filename='assets/js/vendor.min.js') }}"></script>

        <!-- App js -->
        <script src="{{ url_for('static', filename='assets/js/app.min.js') }}"></script>
        
    </body>
</html>